export const AnimalSeed = [
  { name: '개' },
  { name: '고양이' },
  { name: '원숭이' },
  { name: '다람쥐' },
  { name: '쥐' },
  { name: '호랑이' },
  { name: '사자' },
  { name: '퓨마' },
  { name: '미어캣' },
  { name: '코브라' },
  { name: '아나콘다' },
  { name: '늑대' },
  { name: '여우' },
  { name: '사슴' },
  { name: '고라니' },
  { name: '너구리' },
  { name: '제비' },
  { name: '까치' },
  { name: '비둘기' },
  { name: '독수리' },
];
