export const CapitalSeed = [
  { name: '미국' },
  { name: '한국' },
  { name: '일본' },
  { name: '중국' },
  { name: '말레이시아' },
  { name: '프랑스' },
  { name: '이탈리아' },
  { name: '영국' },
  { name: '스페인' },
  { name: '독일' },
  { name: '멕시코' },
  { name: '과테말라' },
  { name: '그리스' },
  { name: '네덜란드' },
  { name: '러시아' },
  { name: '룩셈부르크' },
  { name: '모나코' },
  { name: '브라질' },
  { name: '스웨덴' },
  { name: '싱가포르' },
  { name: '호주' },
  { name: '이집트' },
  { name: '인도' },
  { name: '자메이카' },
  { name: '이란' },
  { name: '사우디아라비아' },
  { name: '북한' },
  { name: '체코' },
  { name: '칠레' },
  { name: '카타르' },
  { name: '콜롬비아' },
  { name: '터키' },
];
