export const FruitSeed = [
  { name: '사과' },
  { name: '포도' },
  { name: '배' },
  { name: '자몽' },
  { name: '레몬' },
  { name: '오렌지' },
  { name: '한라봉' },
  { name: '용과' },
  { name: '참외' },
  { name: '감' },
  { name: '파인애플' },
  { name: '바나나' },
  { name: '복숭아' },
  { name: '살구' },
  { name: '앵두' },
  { name: '딸기' },
  { name: '자두' },
  { name: '곶감' },
  { name: '망고' },
  { name: '체리' },
  { name: '메론' },
  { name: '무화과' },
  { name: '키위' },
  { name: '모과' },
];
